global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'collect'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['192.168.0.50:8801']
        labels: {
              "app": "ionia",
              "env": "test"
          }

  - job_name: 'admin'
    scrape_interval: 5s
    honor_labels: true
    static_configs:
      - targets: ['192.168.0.50:8802']
        labels: {
              "app": "ionia",
              "env": "test"
          }

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
# $ echo "test_metric 123456" | curl --data-binary @- http://localhost:9091/metrics/job/test_job